### ISSUE TITLE
Change card images

### ISSUE THREAD

**Issue by nerdobi** [thomasokken/freecell#1]
Hi there!
I don't know much about coding, but I was wondering if there is an easy way to replace the card images? Thank you!

**Comment by thomasokken** [comment]
Yes, there is: just replace bonded.png (embedded in the app: Freecell.app/Contents/Resources/bonded.png) with your own version. The cards must be arranged in the same pattern, but they don't have to be the same size as the original; the size of the playing board will be adjusted accordingly.

**Comment by thomasokken** [comment]
I'm actually a bit surprised that it is possible to modify the app like that. Freecell.app/Contents/_CodeSignature/CodeResources does contain a hash for that file, so why doesn't the system complain after the file is replaced? Maybe that hash is only checked when the app is run for the first time. But I tried it and it worked, so as long as you're not trying to distribute the modified app, I guess this is OK. If you do want to distribute it, I guess you'd have to re-generate the CodeResources file.

**Comment by nerdobi** [comment]
Yes, it is surprising. Should my modified version ever make it beyond prototype stadium, I will revisit your advice to re-generate the CodeResources file (and possibly generate a new issue because I don't understand anything about coding…). Thank you and have a nice day!

**Comment by thomasokken** [comment]
You too!
